SYMBOLS = {
    "SOLVE": "→",
    "RATIO": ":",
    "BOOL": "?",
    "EQ": "=",
    "GT": ">",
    "GE": "≥",
    "LT": "<",
    "LE": "≤",
    "ADD": "+",
    "SUB": "-",
    "MUL": "•",
    "TRUEDIV": "÷",
    "POW": "^",
    "ROOT": "√",
    "NEG": "-",
    "POS": "+",
}
