SYMBOLS = {
    "GETITEM":"→",
    "EQN":"=",
    "EQ": "⩵",
    "NE": "≠",
    "GT": ">",
    "GE": "≥",
    "LT": "<",
    "LE": "≤",
    "ADD": "+",
    "SUB": "-",
    "MUL": "•",
    "TRUEDIV": "÷",
    "POW": "^",
    "ROOT": "√",
    "NEG": "-",
    "POS": "+",
}
